version: 2.1
jobs:
  build_env:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
                # build the application image
          docker build -t salazardetroya/lestofire:env -f docker/Dockerfile .
          docker push salazardetroya/lestofire:env
  build:
    docker: 
      - image: salazardetroya/lestofire:env
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: install dependencies
          command: |
            source /home/firedrake/firedrake/bin/activate
            pip3 install roltrilinos ROL --user
            pip3 install protobuf==3.8.0 --user
            pip3 install --upgrade numpy --user
        
      # run tests!
      - run:
          name: Run tests
          working_directory: test/
          command: |
            source /home/firedrake/firedrake/bin/activate
            pip3 install -e ../
            gmsh -2 2D_mesh.geo
            gmsh -3 3D_mesh.geo
            pytest .
workflows:
  version: 2
  all:
    jobs:
      - build_env
      - build
