version: 2.1
jobs:
  build:
    docker: 
      - image: firedrakeproject/firedrake:latest
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: install dependencies
          command: |
            wget http://gmsh.info/bin/Linux/gmsh-4.4.1-Linux64.tgz 
            tar -xvf gmsh-4.4.1-Linux64.tgz && \
            mv gmsh-4.4.1-Linux64/bin/* /usr/local/bin/ && \
            mv gmsh-4.4.1-Linux64/share/doc/ /usr/local/share/doc/ && \
            mv gmsh-4.4.1-Linux64/share/man/ /usr/local/share/man/
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get update
            sudo apt-get install -y  python-dev graphviz libgraphviz-dev pkg-config patchelf
            pip3 install roltrilinos ROL --user
            pip3 install termcolor --user
            pip3 install protobuf==3.8.0 --user
            pip3 install --upgrade numpy --user
        
      # run tests!
      - run:
          name: Run tests
          working_directory: test/
          command: |
            source /home/firedrake/firedrake/bin/activate
            pip3 install -e ../
            gmsh -2 2D_mesh.geo
            gmsh -3 3D_mesh.geo
            pytest .

            #workflows:
            #  version: 2.1
            #  all:
            #    jobs:
            #      - test-lestofire
